export const ButtonColors = {
    "dashboard": "Dashboard",
    "folder": "Pasta",
    "toparrow": "fas fa-angle-up",
    "users": "Usuários",
    "company": "Compania",
    "view": "#32CD32",
    "edit": "#4169E1",
    "delete": "#FF6347",
    "question": "rgb(71, 221, 255)",
    "plus": "Mais",
    "print": "Print",
    "table": "Tabela",
    "padrao_qualidade": "Padrão de qualidade",
    "save": "Salvar",
    "cip": "CIP",
    "qip": "QIP",
    "fatura": "Fatura",
    "cadastro": "Cadastro",
    "gerenciamento": "Gerenciamento",
    "solar": "#ff9900",
    "tarifas": "Tarifas",
    "aliquota": "Alíquota"
};

