export const Hints = {
    "dashboard": "Dashboard",
    "folder": "Pasta",
    "toparrow": "fas fa-angle-up",
    "users": "Usuários",
    "company": "Compania",
    "view": "Visualizar",
    "edit": "Editar",
    "delete": "Deletar",
    "plus": "Mais",
    "print": "Print",
    "table": "Tabela",
    "save": "Salvar",
    "cadastro": "Cadastro",
    "regras": "Regras",
    "modulo": "Relatório de Módulos",
    "contato": "Contatos",
    "financeiro": "Relatório Financeiro",
    "vaga": "Vagas",
    "encaminhamento": "Baixar Encaminhamento",
    "apolice": "Relatório Apólices",
    "question": "Adicionar perguntas",
    "answer": "Mostrar respostas"
};

