export const Icons = {
	"dashboard": "fas fa-fw fa-tachometer-alt",
	"folder": "fas fa-fw fa-folder",
	"toparrow": "fas fa-angle-up",
	"users": "fas fa-users",
	"user": "fas fa-user",
	"company": "fas fa-industry",
	"stagecenter": "fas fa-code-branch",
	"view": "fas fa-eye",
	"edit": "fas fa-edit",
	"delete": "fas fa-trash-alt",
	"plus": "fas fa-plus-square",
	"print": "fas fa-print",
	"table": "fas fa-table",
	"info": "fas fa-poll-h",
	"config": "fas fa-wrench",
	"edituser": "fad fa-user-edit",
	"download": "fas fa-download",
	"loadspin": "fas fa-download",
	"loading": "fas fa-circle-notch fa-spin",
	"regras": "fas fa-table",
	"modulo": "fas fa-download",
	"contato": "fas fa-phone",
	"financeiro": "fas fa-download",
	"apolice": "fas fa-download",
	"vaga": "fas fa-user",
	"encaminhamento": "fas fa-download",
	"atividades": "fas fa-tasks"
};

